### ISSUE TITLE
Why PowerShell script when AzureAD supports SCIM for AWS SSO Out-of-the-box? 

### ISSUE THREAD

**Issue by haneef95** [aws-samples/aws-sso-sync-script#4]
Hi,

Why PowerShell script when AzureAD supports SCIM for AWS SSO Out-of-the-box? 

Any additional features/benefits to using this script over what's offered in the link below?

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/aws-single-sign-on-provisioning-tutorial

Thanks,

**Comment by ajkeane-aws** [comment]
Hi,

There is a default time of 40 minutes to sync between Azure and AWS. On Step 15 from the link you provided, "The initial cycle takes longer to perform than subsequent cycles, which occur approximately every 40 minutes as long as the Azure AD". 

This script allows the user to trigger the api endpoint and not have to wait for 40 minutes for the Users/Groups to sync. It assists companies who add users, groups or who enable a user for Privileged Identity Management (PIM) and want the user sent over to AWS immediately rather than waiting for the sync to happen automatically.
